// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuQ58n8YI6iupeGuGuR3LuFf33toIkWuE',
    appId: '1:69540108063:web:654d8e11f13b31dc46422a',
    messagingSenderId: '69540108063',
    projectId: 'flutter-stt',
    authDomain: 'flutter-stt.firebaseapp.com',
    storageBucket: 'flutter-stt.appspot.com',
    measurementId: 'G-RZ5CZ72Q61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6WmryAAu67DPPX6ucswnEhOBlD1k4fLE',
    appId: '1:69540108063:android:b0586091b910d4ee46422a',
    messagingSenderId: '69540108063',
    projectId: 'flutter-stt',
    storageBucket: 'flutter-stt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUj6You3mMQcJR142AiJyW-aWnrXvVrOU',
    appId: '1:69540108063:ios:6772330d55b2656546422a',
    messagingSenderId: '69540108063',
    projectId: 'flutter-stt',
    storageBucket: 'flutter-stt.appspot.com',
    iosClientId: '69540108063-lsi0oe6c5e51i3qn7lins8vn000ricfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.stt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUj6You3mMQcJR142AiJyW-aWnrXvVrOU',
    appId: '1:69540108063:ios:6772330d55b2656546422a',
    messagingSenderId: '69540108063',
    projectId: 'flutter-stt',
    storageBucket: 'flutter-stt.appspot.com',
    iosClientId: '69540108063-lsi0oe6c5e51i3qn7lins8vn000ricfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.stt',
  );
}
